Add step to block changes to specific files

diff --git a/.github/workflows/stars_submission_checks.yml b/.github/workflows/stars_submission_checks.yml
--- a/.github/workflows/stars_submission_checks.yml
+++ b/.github/workflows/stars_submission_checks.yml
@@ -21,5 +21,37 @@ jobs:
         python -m pip install --upgrade pip setuptools wheel
         pip install -r .github/scripts/requirements.txt
 
+    - name: Confirm only changes in allowed files
+      run: |
+        
+        # Commit with most up to date common files. Do not change unless you are working on the post-program integration team or have explicit permission from someone who is.
+        BASE_COMMIT="1ee10023ab63bcb9e9ca14395f2528c9bc29e181" #12/7/2024, "Fix python script path in workflow"
+        
+        # Get list of changed files between the base commit and current commit
+        git diff --name-only $BASE_COMMIT ${{ github.sha }} > changed_files.txt
+        
+        # List of files teams shouldn't change
+        BLOCKED_FILES=(".github/scripts/requirements.txt" "verilog/rtl/Makefile")
+
+        # Initialize a flag to detect if any disallowed files were changed
+        DISALLOWED_FILE_CHANGE_FOUND=false
+
+        echo "Checking for blocked files..."
+
+        # Check each file and list problems
+        for FILE in "${BLOCKED_FILES[@]}"; do
+          if grep -qx "$FILE" changed_files.txt; then
+            echo "Found problematic file: $FILE"
+            DISALLOWED_FILE_CHANGE_FOUND=true
+          fi
+        done
+
+        if [ "$DISALLOWED_FILE_CHANGE_FOUND" = true ]; then
+          echo "Push includes blocked files. Failing the workflow."
+          exit 1
+        else
+          echo "No blocked files were changed."
+        fi
+
     - name: Confirm Environment
       run: python ./.github/scripts/test_environment.py
